# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14abf8c5beaae5d74c6aab7f7b2ca99c38ca3b943dad2dd8a0751bed7f51a8b7709dab56c4a347a06c74f83aaca8511501878eec43d345412181cc4fd2c3b1b4

test:
  secret_key_base: e32e310cccda72b22fcdec99323a0b591f9761d697b233c1238d94bb26d6648821cf53c8f6d45358d394cc8201b8cded33b0de6cf5a3cc3b06d51829f2665b68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
